'use strict';
export type plazaCell = {
  key: string;
  module: Object;
};
var CellArray: Array<plazaCell> = [{
key:"FF_BrandDetailGoodCell_01",
module:require('./FF_BrandDetailGoodCell/FF_BrandDetailGoodCell_01')
},
{
key:"FF_BrandDetailImageCell_01",
module:require('./FF_BrandDetailImageCell/FF_BrandDetailImageCell_01')
},
{
key:"FF_BrandDetailIntroduceCell_01",
module:require('./FF_BrandDetailIntroduceCell/FF_BrandDetailIntroduceCell_01')
},
{
key:"FF_BrandDetailSectionCell_01",
module:require('./FF_BrandDetailSectionCell/FF_BrandDetailSectionCell_01')
},
{
key:"FF_BrandDetailStoreCell_01",
module:require('./FF_BrandDetailStoreCell/FF_BrandDetailStoreCell_01')
},
{
key:"FF_PlazaActivityCell_0",
module:require('./FF_PlazaActivityCell/FF_PlazaActivityCell_0')
},
{
key:"FF_PlazaActivityCell_1000265",
module:require('./FF_PlazaActivityCell/FF_PlazaActivityCell_1000265')
},
{
key:"FF_PlazaActivityCell_1000772",
module:require('./FF_PlazaActivityCell/FF_PlazaActivityCell_1000772')
},
{
key:"FF_PlazaActivityCell_1100079",
module:require('./FF_PlazaActivityCell/FF_PlazaActivityCell_1100079')
},
{
key:"FF_PlazaBaseInfoCell_0",
module:require('./FF_PlazaBaseInfoCell/FF_PlazaBaseInfoCell_0')
},
{
key:"FF_PlazaBaseInfoCell_1000265",
module:require('./FF_PlazaBaseInfoCell/FF_PlazaBaseInfoCell_1000265')
},
{
key:"FF_PlazaBaseInfoCell_1000772",
module:require('./FF_PlazaBaseInfoCell/FF_PlazaBaseInfoCell_1000772')
},
{
key:"FF_PlazaBaseInfoCell_1100079",
module:require('./FF_PlazaBaseInfoCell/FF_PlazaBaseInfoCell_1100079')
},
{
key:"FF_PlazaCouponCell_0",
module:require('./FF_PlazaCouponCell/FF_PlazaCouponCell_0')
},
{
key:"FF_PlazaFavourableCell_01",
module:require('./FF_PlazaFavourableCell/FF_PlazaFavourableCell_01')
},
{
key:"FF_PlazaSuggestStoreCell_0",
module:require('./FF_PlazaSuggestStoreCell/FF_PlazaSuggestStoreCell_0')
},
{
key:"FF_PlazaSuggestStoreCell_1000265",
module:require('./FF_PlazaSuggestStoreCell/FF_PlazaSuggestStoreCell_1000265')
},
{
key:"FF_PlazaSuggestStoreCell_1000772",
module:require('./FF_PlazaSuggestStoreCell/FF_PlazaSuggestStoreCell_1000772')
},
{
key:"FF_PlazaSuggestStoreCell_1100079",
module:require('./FF_PlazaSuggestStoreCell/FF_PlazaSuggestStoreCell_1100079')
},
{
key:"UF_AdvertisementCell_01",
module:require('./UF_AdvertisementCell/UF_AdvertisementCell_01')
},
{
key:"UF_AdvertisementCell_02",
module:require('./UF_AdvertisementCell/UF_AdvertisementCell_02')
},
{
key:"UF_AppChoice_0",
module:require('./UF_AppChoice/UF_AppChoice_0')
},
{
key:"UF_AppChoice_01",
module:require('./UF_AppChoice/UF_AppChoice_01')
},
{
key:"UF_AppChoice_02",
module:require('./UF_AppChoice/UF_AppChoice_02')
},
{
key:"UF_AppChoice_03",
module:require('./UF_AppChoice/UF_AppChoice_03')
},
{
key:"UF_ColTwoNav_01",
module:require('./UF_ColTwoNav/UF_ColTwoNav_01')
},
{
key:"UF_FlashCell_01",
module:require('./UF_FlashCell/UF_FlashCell_01')
},
{
key:"UF_FlashCell_03",
module:require('./UF_FlashCell/UF_FlashCell_03')
},
{
key:"UF_PlazaInfo_0",
module:require('./UF_PlazaInfo/UF_PlazaInfo_0')
},
{
key:"UF_pm25_beijing",
module:require('./UF_pm25/UF_pm25_beijing')
},
{
key:"UF_pm25_guangzhou",
module:require('./UF_pm25/UF_pm25_guangzhou')
},
{
key:"UF_weather_beijing",
module:require('./UF_weather/UF_weather_beijing')
},
{
key:"UF_weather_guangzhou",
module:require('./UF_weather/UF_weather_guangzhou')
},
{
key:"UF_weather_shanghai",
module:require('./UF_weather/UF_weather_shanghai')
},
{
key:"UF_AppChoice_0",
module:require('../../FOAP/Component/UF_AppChoice/UF_AppChoice_0')
},
];
const plazaCells = {};
CellArray.forEach(cell => {
  plazaCells[cell.key] = cell.module;
});

const stylelist = {
  plazaCells,
}
module.exports = stylelist;